services:
  backend:
    build: .
    container_name: backend
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./:/src
    environment:
      - TZ=UTC
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=pedrovieirafdev@gmail.com 
      - EMAIL_PASS=dlvqzfogyesfityv
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
